// Run after applying the kit and building program. No global VSCE or pnpm needed.
import { cp, mkdir, mkdtemp, readFile, writeFile } from 'node:fs/promises'
import { join, resolve } from 'node:path'
import { inventory, archive, sha256 } from './archive.mjs'
const program=resolve(process.argv[2]??'.')
const pkg=JSON.parse(await readFile(join(program,'package.json'),'utf8'))
for(const value of [pkg.name,pkg.publisher,pkg.version]) if(!/^[a-zA-Z0-9_.-]+$/.test(value)) throw new Error('EXTENSION_ID_INVALID')
if(!pkg.extensionDependencies?.includes('kiro.kiroAgent')) throw new Error('KIRO_AGENT_DEPENDENCY_REQUIRED')
const portable=join(program,'portable')
const manifest=JSON.parse(await readFile(join(portable,'manifest.json'),'utf8'))
const actual=await inventory(portable)
if(actual.length!==Object.keys(manifest.files).length+1) throw new Error('PORTABLE_INVENTORY_MISMATCH')
for(const file of actual) if(file.name!=='manifest.json' && (manifest.files[file.name]?.sha256!==file.sha256 || manifest.files[file.name]?.bytes!==file.bytes)) throw new Error('PORTABLE_HASH_MISMATCH')
const out=resolve(process.argv[3]??join(program,'dist'))
await mkdir(out,{recursive:true})
const stage=await mkdtemp(join(out,'.vsix-stage-'))
await mkdir(join(stage,'extension/dist/webview'),{recursive:true})
for(const file of ['package.json','dist/extension.js','dist/webview/main.js']) await cp(join(program,file),join(stage,'extension',file))
await cp(join(program,'media'),join(stage,'extension/media'),{recursive:true})
await cp(portable,join(stage,'extension/portable'),{recursive:true})
const escaped=value=>String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;')
await writeFile(join(stage,'[Content_Types].xml'),`<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">${['json','js','cjs','mjs','node','sql','md','svg','png','html','vsixmanifest'].map(ext=>`<Default Extension="${ext}" ContentType="application/octet-stream"/>`).join('')}</Types>`)
await writeFile(join(stage,'extension.vsixmanifest'),`<?xml version="1.0"?><PackageManifest Version="2.0.0" xmlns="http://schemas.microsoft.com/developer/vsx-schema/2011"><Metadata><Identity Language="en-US" Id="${pkg.name}" Version="${pkg.version}" Publisher="${pkg.publisher}" TargetPlatform="win32-x64"/><DisplayName>${escaped(pkg.displayName)}</DisplayName><Description xml:space="preserve">${escaped(pkg.description)}</Description><Properties><Property Id="Microsoft.VisualStudio.Code.Engine" Value="^1.131.0"/><Property Id="Microsoft.VisualStudio.Code.TargetPlatform" Value="win32-x64"/></Properties></Metadata><Installation><InstallationTarget Id="Microsoft.VisualStudio.Code"/></Installation><Dependencies/><Assets><Asset Type="Microsoft.VisualStudio.Code.Manifest" Path="extension/package.json" Addressable="true"/></Assets></PackageManifest>`)
const files=await inventory(stage)
for(const file of files) if(/\.(?:db|sqlite|log|map)$|(?:^|\/)(?:\.env|connection\.json|node_modules\/\.cache)(?:$|\/)/.test(file.name)) throw new Error('PACKAGE_PRIVATE_FILE_DENIED')
const output=join(out,`${pkg.name}-${pkg.version}-win32-x64-${sha256(JSON.stringify(files)).slice(0,12)}.vsix`)
const report=await archive(stage,output)
await writeFile(join(out,'program-vsix-receipt.json'),JSON.stringify(report,null,2))
console.log(JSON.stringify(report))
